language: java

jdk:
  - openjdk8

deploy:
  provider: heroku
  api_key:
    secure: QPpF0cTYmrNF89EkKHHNRe8KL3EAhCYjTA5RYNDu4eiulNqhYGGGQqkKP/OHFYzI9d9VIev44N5grFAITT9Tu4sirHAwVaIji7Dk5X5N1g1oViSdT1kqN+3ylUajxt5MxVwQTuIoErdJtmCXuwosKGLoSA1UepbS3Jvtb2Xoreq4TOvyIQ/NprnrZTfCVtQsTeOvdn24Ybq+Ha+P9l8Q+DacM13sz3IihU5Xjhs7bhczWPnJ7gNlDR+wyZE26Wvo9HvtGtM2k6u2JDVm6PyaBYOoXnQyx4WyZUOCrNzKfy2w4AxnQOpQxOOHbi9kQfpb42P8DB8y5h6PyYXSOPhgqL12cReXcPYj5njJg0hILTlTWhr43U0FnBN5CFDa8eqzTTU36QBz2Id22yGmI1/dab3VE4+N2LjIDdAgAfHnhrBln1AKAqsawDHyjtxJMSFp1EE5mqYrn2oaJjiDuD+2rSY9cysn/xMTX1KmKr78DdxYjdpHv1IYv+5ekbgGlFP+d7mjdFhY7u9O+qPs5kubeDoow84ezKF8yVCDjrJYfgQy3b3AwDsujHKPQ16PfMruULSxm9uYCqN0atQl1SouezpSIQGrBoWCQWs3RY/hR1CdTlVzS6Au7bc/bm8Ev9WXLokxA85CTGIeCWrnmxqm5MqQs8Kf1wZHdCjInrQAp9o=
  app: test-a-manetta
  on:
    branch: master